FROM microsoft/mssql-tools as mssql
FROM alpine as new-alpine
FROM php:7.1-cli-alpine
COPY configure.sh /
COPY php.ini /usr/local/etc/php
COPY zz_01-additional.ini /usr/local/etc/php/conf.d/
COPY zz_02-xdebug.ini /usr/local/etc/php/conf.d/
COPY --from=mssql /opt/mssql-tools/ /opt/mssql-tools/
COPY --from=new-alpine /etc/ssl/cert.pem /etc/ssl/cert.pem

ENV COMPOSER_DIR=/.composer \
    SYMFONY_DIR=/.symfony \
    TOOLS_DIR=/tools/

RUN HOME=/ \
    && /configure.sh \
    && rm /configure.sh \
    && docker-php-source extract \
    && mkdir $COMPOSER_DIR $SYMFONY_DIR $TOOLS_DIR \
    && apk add --no-cache $PHPIZE_DEPS \
    && pecl install xdebug-2.9.8 \
    && docker-php-ext-enable xdebug \
    && apk del $PHPIZE_DEPS \
    && rm -r /tmp/pear/cache/* /tmp/pear/download/* \
    && docker-php-source delete \
    # Composer
    && curl --silent --fail-early https://getcomposer.org/installer | php -- --1 --install-dir=/usr/local/bin --filename=composer \
    # Symfony binary
    # QA - Globally https://twitter.com/s_bergmann/status/999635212723212288
    && mkdir --parents /tools/php-cs-fixer && composer require --working-dir=/tools/php-cs-fixer friendsofphp/php-cs-fixer \
    && chmod -R o+rwx $COMPOSER_DIR $SYMFONY_DIR $TOOLS_DIR

WORKDIR /app


