FROM microsoft/mssql-tools as mssql
FROM alpine as new-alpine
FROM php:7.1-fpm-alpine as prod

COPY configure.sh /
COPY www.conf /usr/local/etc/php-fpm.d/www.conf
COPY php.ini /usr/local/etc/php/conf.d
COPY zz_additional.ini /usr/local/etc/php/conf.d/
COPY --from=mssql /opt/microsoft/ /opt/microsoft/
COPY --from=mssql /opt/mssql-tools/ /opt/mssql-tools/
COPY --from=mssql /usr/lib/libmsodbcsql-13.so /usr/lib/libmsodbcsql-13.so
COPY --from=new-alpine /etc/ssl/cert.pem /etc/ssl/cert.pem

RUN /configure.sh \
    && rm /configure.sh
WORKDIR /var/www

FROM prod as dev
COPY docker-dev-entrypoint /usr/local/bin

RUN apk add --no-cache $PHPIZE_DEPS \
        && pecl install xdebug-2.9.8 \
        && docker-php-ext-enable xdebug \
        && apk del $PHPIZE_DEPS

ENTRYPOINT ["docker-dev-entrypoint"]
CMD ["php-fpm"]